apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fileupdatestest-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fileupdatestest-component
    app.kubernetes.io/part-of: fileupdatestest
  name: fileupdatestest-component
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: python-app
    app.kubernetes.io/instance: fileupdatestest-component
status:
  loadBalancer: {}
